
version: 2

# models:
#     - name: weather_by_trips_all_time
#       description: "Report that aggregates all trips by weather type"
#       columns:
#           - name: conditions
#             description: "Weather condition"
#             tests:
#                 - unique
#                 - not_null
#           - name: num_trips
#             description: "Number of trips aggregated for all-time"
#             tests:
#                 - not_null