
version: 2

models:
    - name: weather
      description: "Structures the JSON weather data"
      columns:
          - name: observation_key
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: city_name
            description: "City where the weather observation was recorded"
            tests:
                - not_null
                - accepted_values:
                    values: ['New York']